version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "week"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "week"
      
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
