version: '3.9'

services:
  ros_node:
    build:
      context: .
    command: ros2 run node watchdog_node_001
    restart: always

  ros_robot:
    build:
      context: .
    command: ros2 run robot watchdog_node_001
    restart: always

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
