version: "3.7"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - app
      - redis
      - postgres
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf

  app:
    container_name: app
    image: app:dev
    depends_on:
      - postgres
      - redis
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      cache_from:
        - app:dev
    command: poetry run uvicorn app.main:start --host 0.0.0.0 --port 8080
    restart: unless-stopped
    env_file: .env

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  postgres:
    container_name: db
    image: postgres:latest
    ports:
      - "5432"
    env_file: .env
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    restart: unless-stopped

volumes:
  redis-data:
  postgres-data:
