version: '3.9'

services:
  rosnode:
    build: .
    volumes:
      - .:/app
    command: ros2 run core watchdog-node-001

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - cache:/data


volumes:
  cache:
    driver: local
