version: '3.9'

services:
  ros_core:
    image: ghcr.io/the-dark-limit/watchdog-node:release
    build:
      context: .
    command: ros2 run core core
    restart: always

  rq_worker:
    image: ghcr.io/the-dark-limit/watchdog-node:release
    build:
      context: .
    command: rq worker --with-scheduler
    restart: always

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
