version: "3.8"


services:
  watchdog:
    image: "watchdog-backend:dev"
    container_name: "WatchDog"
    restart: unless-stopped
    build:
      target: dev_build
      context: .
      dockerfile: ./docker/django/Dockerfile
      args:
        DJANGO_ENV: dev
    ports:
      - "80:8000"
    volumes:
      - django-static:/var/www/django/static
      - .:/app
    depends_on:
      - postgres
      - redis
    networks:
      - watchdog-network
    env_file: config/.env
    environment:
      - config/.env

    command: python -Wd manage.py runserver 0.0.0.0:8000
    healthcheck:
      test: |
        /usr/bin/test $$(
          /usr/bin/curl --fail http://localhost:8000/health/?format=json
          --write-out "%{http_code}" --silent --output /dev/null
        ) -eq 200
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  postgres:
    image: "postgres:latest"
    restart: unless-stopped

    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - watchdog-network

  redis:
    restart: unless-stopped
    image: "redis:latest"
    environment:
      - config/.env
    ports:
      - "6379:6379"
    networks:
      - watchdog-network


networks:
  watchdog-network:

volumes:
  pgdata:
  django-static:
