version: '3.4'

services:
  nginx:
    restart: unless-stopped
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:8000"
    networks:
      - watchdog

  watchdogbackend:
    restart: unless-stopped
    image: watchdogbackend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      production: 'true'
    env_file:
      - ./config/.env
    ports:
      - "8000:8000"
    networks:
      - watchdog

  redis:
    restart: unless-stopped
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - watchdog

  postgres:
    restart: unless-stopped
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - watchdog

volumes:
  postgres_data:

networks:
  watchdog:
