version: '3.9'

services:
  rosnode:
    build:
      context: .

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data


volumes:
  cache:
    driver: local
