[tool.poetry]
name = "watchdog-node"
description = "WatchDog Main Node"
version = "0.1.0"
authors = ["NickiHell <nickihell@ya.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11.3"

django = { version = "^4.2", extras = ["argon2"] }
django-ninja = "*"
django-split-settings = "^1.2"
django-axes = "^6.0"
django-csp = "^3.7"
django-health-check = "^3.16"
django-http-referrer-policy = "^1.1"
django-permissions-policy = "^4.14"

uvicorn = "*"
gunicorn = "*"
python-decouple = "^3.7"
django-loguru = "^1.0.3"
structlog = "*"

torch = "*"
transformers = "*"

aiohttp = "^3.8.3"
aiojobs = "^1.1.0"
aiofiles = "^23.1.0"
aiogram = "*"

psutil = "^5.9.4"
i3pyblocks = "^2020.10.3"
psycopg-binary = "^3.1.8"
psycopg2-binary = "^2.9.4"
redis = "^4.5.3"
dbus-next = "^0.2.3"
i3ipc = "^2.2.1"
aionotify = "^0.2.0"
pulsectl = "^23.5.2"


[tool.poetry.group.dev.dependencies]
django-debug-toolbar = "^4.1"
django-querycount = "^0.8"
django-migration-linter = "^4.1"
django-extra-checks = "^0.13"
django-coverage-plugin = "^2.0"
django-stubs = "^4.2"
django-stubs-ext = "^4.2"

nplusone = "^1.0"

wemake-python-styleguide = "^0.18"

pytest = "^7.4"
pytest-django = "^4.5"
pytest-cov = "^4.1"
pytest-randomly = "^3.12"
pytest-deadfixtures = "^2.2"
pytest-timeout = "^2.1"
django-test-migrations = "^1.2"
hypothesis = "^6.79"

mypy = "^1.3"
yamllint = "^1.27"
safety = "^2.1"
dotenv-linter = "^0.4"
dump-env = "^1.3"
ipython = "^8.10"
black = "^23.3.0"
ruff = "^0.0.275"

[tool.ruff]
select = [
  "E", # pycodestyle errors
  "W", # pycodestyle warnings
  "F", # pyflakes
  "B", # flake-bugbear
  "Q", # flake8-quotes
  "I", # isort
  "PT", # flake8-pytest-style
  "RET", # flake8-return
  "SIM", # flake8-simplify
  "FBT", # flake8-boolean-trap
  "C4", # flake8-comprehensions
  "PIE", # flake8-pie
  "TRY", # tryceratops
  "RUF", # ruff
  "PL", # pylint
  "UP", # pyupgrade
  "C90", # mccabe
  "COM", # flake8-commas
  "INP", # flake8-no-pep420
  "TID", # flake8-tidy-imports
  "PTH", # flake8-use-pathlib
  "ERA", # eradicate
  "EM", # flake8-errmsg
  "FA", # flake8-future-annotations
]

ignore = [
  "E501", # Never enforce line length
  "RET504", # Unnecessary variable assignment before `return` statement
  "RUF001", # ruff unicode specific rules
  "RUF002", # ruff unicode specific rules
  "RUF003", # ruff unicode specific rules
  "TRY200", # Duplicates B904 warning
]

unfixable = [
  "B", # Avoid trying to fix flake8-bugbear violations.
  "ERA", # Avoid deleting commented-out code
]

line-length = 140
target-version = "py311"

[tool.ruff.per-file-ignores]
"apps/linux/services/sway/*" = [
  "ERA001", # fix later
]
"*/settings/*" = [
  "ERA001", # Found commented-out code
  "PLW1508", # Invalid type for environment variable default
  "FBT003", # Boolean positional value in function call
]
"tests/*" = [
  "ARG001", # Unused function argument
  "ARG002", # Unused method argument
  "ERA001", # Found commented-out code
  "PLR0913", # Too many arguments to function call
  "PLR2004", # Magic value used in comparison
  "INP001", # File is part of an implicit namespace package
]
"*/migrations/*" = [
  "INP001", # Add an `__init__.py`
  "ERA001", # Found commented-out code
  "RUF012", # Mutable class attributes should be annotated with `typing.ClassVar`
]

[tool.ruff.flake8-bugbear]
extend-immutable-calls = ["ninja.Query"]

[tool.ruff.flake8-quotes]
inline-quotes = "single"

[tool.ruff.mccabe]
max-complexity = 10

[tool.ruff.isort]
lines-after-imports = 2


[tool.black]
line-length = 90
target-version = ["py311"]
skip-string-normalization = true
exclude = ".git/|media/"


[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "image_service.settings"
norecursedirs = "*.egg .eggs .* dist build docs __pycache__ etc"
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = true
addopts = [
  "--import-mode=importlib",
  "--strict-markers",
  "--strict-config",
  "--tb=short",
]
filterwarnings = [
  "ignore::DeprecationWarning:pytest_freezegun:17",
  "ignore::DeprecationWarning:concurrency.config:71",
  "ignore::DeprecationWarning:celery.utils.imports:145",
  "ignore::DeprecationWarning:kombu.utils.compat:82",
]


[tool.mypy]
plugins = ["pydantic.mypy"]

allow_redefinition = false
check_untyped_defs = true
disallow_untyped_decorators = true
disallow_any_explicit = false
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_untyped_calls = true
ignore_errors = false
ignore_missing_imports = true
implicit_reexport = true
local_partial_types = true
strict_optional = true
strict_equality = true
no_implicit_optional = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unreachable = true
warn_no_return = true
follow_imports = "silent"
pretty = true
show_error_codes = true
show_column_numbers = true

[[tool.mypy.overrides]]
disallow_incomplete_defs = false

[tool.pydantic-mypy]
init_forbid_extra = false
init_typed = false
warn_required_dynamic_aliases = true
warn_untyped_fields = true


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
