[tool.poetry]
name = "watchdog-node"
description = "WatchDog Main Node"
version = "0.1.0"
authors = ["NickiHell <nickihell@ya.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

django = { version = "^4.2", extras = ["argon2"] }
django-ninja = "^1.0"
django-split-settings = "^1.2"
django-axes = "^6.0"
django-csp = "^3.7"
django-health-check = "^3.16"
django-http-referrer-policy = "^1.1"
django-permissions-policy = "^4.14"

uvicorn = "^1.0"
gunicorn = "^1.0"
python-decouple = "^3.7"
django-loguru = "^1.0.3"
structlog = "^23.1.0"


[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
ruff = "^0.0.275"

[tool.ruff]
select = [
  "E", # pycodestyle errors
  "W", # pycodestyle warnings
  "F", # pyflakes
  "B", # flake-bugbear
  "Q", # flake8-quotes
  "PT", # flake8-pytest-style
  "RET", # flake8-return
  "SIM", # flake8-simplify
  "FBT", # flake8-boolean-trap
  "C4", # flake8-comprehensions
  "PIE", # flake8-pie
  "TRY", # tryceratops
  "RUF", # ruff
  "PL", # pylint
  "DTZ", # flake8-datetimez
  "UP", # pyupgrade
  "C90", # mccabe
  "COM", # flake8-commas
  "INP", # flake8-no-pep420
  "TID", # flake8-tidy-imports
  "PTH", # flake8-use-pathlib
  "ERA", # eradicate
]

ignore = [
  "Q000",
  "E501", # Never enforce line length
  "RET504", # Unnecessary variable assignment before `return` statement
  "RUF001", # ruff unicode specific rules
  "RUF002", # ruff unicode specific rules
  "RUF003", # ruff unicode specific rules
  "TRY003", # Avoid specifying long messages outside the exception class
]

unfixable = [
  "B", # Avoid trying to fix flake8-bugbear violations.
  "ERA", # Avoid deleting commented-out code
]

extend-exclude = []

line-length = 120
target-version = "py311"

[tool.ruff.mccabe]
max-complexity = 10

[tool.isort]
profile = "black"
line_length = 120
lines_after_imports = 2
ensure_newline_before_comments = true
known_third_party = ["image_service_client"]

[tool.black]
line-length = 120
target-version = ["py311"]
skip-string-normalization = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
