[tool.poetry]
name = "watchdog-backend"
description = "WatchDog Backend"
version = "0.1.0"
readme = "README.md"
authors = ["nickihell.online"]

[build-system]
requires = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"



[tool.poetry.dependencies]
python = "^3.10.8"

django = { version = "^4.1", extras = ["argon2"] }
django-split-settings = "^1.2"
django-axes = "^5.39"
django-csp = "^3.7"
django-health-check = "^3.16"
django-http-referrer-policy = "^1.1"
django-permissions-policy = "^4.13"
django-stubs-ext = "^0.7"

gunicorn = "^20.0"
python-decouple = "^3.6"
structlog = "^22.1"
django-loguru = "^1.0.3"
aiohttp = "^3.8.3"
aiojobs = "^1.1.0"
aiofiles = "^22.1.0"
djangorestframework = "^3.14.0"
aiogram = "^2.22.2"

psutil = "^5.9.3"
i3pyblocks = "^2020.10.3"
psycopg-binary = "^3.1.3"
psycopg2-binary = "^2.9.4"
redis = "^4.3.4"
djangorestframework-jsonapi = "^6.0.0"
dbus-next = "^0.2.3"
i3ipc = "^2.2.1"
aionotify = "^0.2.0"
pulsectl = "^22.3.2"


[tool.poetry.group.dev.dependencies]
django-debug-toolbar = "^3.6"
django-querycount = "^0.7"
django-migration-linter = "^4.1"
django-extra-checks = "^0.12"
django-coverage-plugin = "^2.0"
nplusone = "^1.0"

wemake-python-styleguide = "^0.16"
doc8 = "^1.0"

pytest = "^7.1"
pytest-django = "^4.5"
pytest-cov = "^3.0"
pytest-randomly = "^3.12"
pytest-deadfixtures = "^2.2"
pytest-timeout = "^2.1"
django-test-migrations = "^1.2"
hypothesis = "^6.54"

mypy = "^0.971"
django-stubs = "^1.12"

yamllint = "^1.27"
safety = "^2.1"
dotenv-linter = "^0.4"
polint = "^0.4"
dennis = "^1.1"
dump-env = "^1.3"
ipython = "^8.4"
black = "^22.10.0"
isort = "^5.10.1"
ruff = "*"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
sphinx = "^5.1"
sphinx-autodoc-typehints = "^1.19"
tomli = "^2.0"

[tool.ruff]
line-length = 90

# Enable Flake's "E" and "F" codes by default.
select = ["E", "F"]
ignore = []

# Exclude a variety of commonly ignored directories.
exclude = [
  ".bzr",
  ".direnv",
  ".eggs",
  ".git",
  ".hg",
  ".mypy_cache",
  ".nox",
  ".pants.d",
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  "__pypackages__",
  "_build",
  "buck-out",
  "build",
  "dist",
  "node_modules",
  "venv",
]
per-file-ignores = { }

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.10.
target-version = "py310"

[tool.isort]
line_length = 90
combine_as_imports = true
balanced_wrapping = true
lines_after_imports = 2
include_trailing_comma = true
multi_line_output = 5

import_heading_stdlib = "built-in"
import_heading_thirdparty = "external"
import_heading_firstparty = "project"
import_heading_localfolder = "app"


[tool.commitizen]
version = "3.0.0"
annotated_tag = true
update_changelog_on_bump = true
bump_message = "bump: $current_version → $new_version"  # keep in sync with .github/workflows/bumpversion.yml!!!
changelog_start_rev = "0.11.0"
