[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.nitpick]
style = "https://raw.githubusercontent.com/wemake-services/wemake-python-styleguide/master/styles/nitpick-style-wemake.toml"


[tool.poetry]
name = "WatchDog"
description = ""
version = "0.1.0"
readme = "README.md"
authors = [""]


[tool.poetry.dependencies]
python = "^3.10"

django = "*"
django-split-settings = "*"
django-axes = "*"
django-csp = "*"
django-health-check = "*"
django-http-referrer-policy = "*"
django-permissions-policy = "*"
django-stubs-ext = "*"
djangorestframework = "*"
drf-spectacular = "*"

psycopg2-binary = "*"
gunicorn = "*"
python-decouple = "*"
bcrypt = "*"
structlog = "*"

uvicorn = "*"
aiogram = "*"


[tool.poetry.group.dev.dependencies]
isort = "*"
black = "*"
django-debug-toolbar = "*"
django-querycount = "*"
django-migration-linter = "*"
django-extra-checks = "*"
django-coverage-plugin = "*"
nplusone = "*"

wemake-python-styleguide = "*"
flake8-pytest-style = "*"
flake8-django = "*"
flake8-logging-format = "*"
nitpick = "*"

pytest = "*"
pytest-django = "*"
pytest-cov = "*"
pytest-randomly = "*"
pytest-deadfixtures = "*"
pytest-testmon = "*"
pytest-timeout = "*"
django-test-migrations = "*"
hypothesis = "*"

mypy = "*"
django-stubs = "*"

yamllint = "*"
safety = "*"
dotenv-linter = "*"
polint = "*"
dennis = "*"
dump-env = "*"
ipython = "*"
taskipy = "*"
flakeheaven = "*"

[tool.flakeheaven]
base = "https://raw.githubusercontent.com/flakeheaven/flakeheaven/main/pyproject.toml"
extended_default_ignore = []
format = "grouped"
max_complexity = 10
max_function_length = 30
max_line_length = 90
show_source = true
statistics = true

[tool.flakeheaven.plugins]
flake8 = ["+*"]
flake8-functions = ["+*"]
flake8-eradicate = ["+*"]
flake8-bugbear = ["+*"]
flake8-comprehensions = ["+*"]
flake8-commas = ["+*"]
flake8-quotes = ["+*"]
mccabe = ["+*"]
pep8-naming = ["+*"]
pycodestyle = ["+*", "-E501"]
wemake-python-styleguide = ["+*", "-WPS305"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "server.settings.testing"
addopts = ["--reuse-db"]

[tool.taskipy.tasks]
flakehell = "flakehell lint --jobs 4"
pytest = "pytest tests --disable-pytest-warnings"
mypy = "mypy server"
