[tool.poetry]
name = "watchdog"
version = "0.1.0"
description = ""
authors = ["NickiHell <nickihell@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
transformers = "^4.8.2"
torch = "^1.9.0"
python-telegram-bot = "^13.7"
python-dotenv = "^0.18.0"
fastapi = "^0.67.0"
uvicorn = "^0.14.0"
aerich = "^0.5.4"
tortoise-orm = "^0.17.5"
asyncpg = "^0.23.0"
loguru = "^0.5.3"
fastapi-admin = "^1.0.2"
hvac = "^0.11.0"
tensorboard = "^2.5.0"
python-multipart = "^0.0.5"

[tool.poetry.dev-dependencies]
ipython = "^7.25.0"
pytest = "^6.2.4"
taskipy = "^1.8.1"
pylint = "^2.9.5"
mypy = "^0.910"
flake8 = "^3.9.2"
flake8-functions = "^0.0.6"
wemake-python-styleguide = "^0.15.3"
flakehell = "^0.9.0"
isort = "^5.9.2"
pytest-cov = "^2.12.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.flakehell]
#baseline = ".flakehell_baseline"
extended_default_ignore=[] # https://github.com/flakehell/flakehell/issues/10
format = "grouped"
max_complexity = 10
max_function_length = 24
max_line_length = 120
show_source = true
statistics = true

[tool.flakehell.plugins]
flake8 = ["+*"]
flake8-functions = ["+*"]
flake8-eradicate = ["+*"]
flake8-bugbear = ["+*"]
flake8-comprehensions = ["+*"]
flake8-commas = ["+*"]
flake8-quotes = ["+*"]
mccabe = ["+*"]
pep8-naming = ["+*"]
pycodestyle = ["+*", "-E501"]
wemake-python-styleguide = ["+*", "-WPS305"]


[tool.taskipy.tasks]
isort = "isort --check-only app"
flakehell = "flakehell lint --jobs 4"
pytest = "pytest tests"
mypy = "mypy app"
